#!/usr/bin/env bash
# ==============================================================================
#  EasySB 发布服务器置备 / provision the EasySB release server
# ------------------------------------------------------------------------------
#  在一台 Debian / Ubuntu 主机上准备软件源站点，全部步骤可重复执行：
#    - 安装 caddy，写站点配置，用自动签发的证书对外提供 HTTPS
#    - 建立站点根目录与 linux / pacman / bin 三个子目录
#    - 安装 vsftpd 并建一个只能写站点根的 FTP 账号，供发布工作流上传
#
#  Prepares a Debian / Ubuntu host to serve the package sources. Every step is
#  idempotent:
#    - install caddy, write the site config, serve HTTPS with an automatic certificate
#    - create the site root and its linux / pacman / bin subtrees
#    - install vsftpd and one FTP account confined to the site root, for the release
#      workflow to upload through
#
#  用法 / Usage:
#    SITE_DOMAIN=sb.kejizero.xyz FTP_PASSWORD=... bash provision.sh
#
#  需要 root；FTP_PASSWORD 必填，用于建立那个手工上传用的 FTP 账号。发布工作流已改走 SSH
#  （见 .github/workflows/easysb-go-release.yml），不再用这个账号。
#  Run as root. FTP_PASSWORD is required for that manual-upload FTP account. The release
#  workflow ships over SSH now (see .github/workflows/easysb-go-release.yml) and no longer
#  uses it.
# ==============================================================================

set -euo pipefail

SITE_DOMAIN="${SITE_DOMAIN:-sb.kejizero.xyz}"
WEBROOT="${WEBROOT:-/var/www/${SITE_DOMAIN}}"
FTP_USER="${FTP_USER:-easysb}"
FTP_PASSWORD="${FTP_PASSWORD:-}"
FTP_SHELL="${FTP_SHELL:-/usr/sbin/nologin}"
FTP_PASV_MIN="${FTP_PASV_MIN:-40000}"
FTP_PASV_MAX="${FTP_PASV_MAX:-40100}"

TLS_CERT=/etc/ssl/certs/easysb-ftp.crt
TLS_KEY=/etc/ssl/private/easysb-ftp.key
CADDYFILE=/etc/caddy/Caddyfile
VSFTPD_CONF=/etc/vsftpd.conf
# 站点首页由这份 Caddy browse 模板渲染：它同时画出目录列表和安装说明。模板随发布上传
# 到 dist/repo/.easysb/，置备只在它缺失时放一份占位符，免得刚置备好的站点直接 500。
# The home page is rendered by this Caddy browse template, which draws the directory
# listing and the install notes together. The release uploads it to dist/repo/.easysb/;
# provisioning only drops a placeholder when it is missing, so a fresh box never 500s.
BROWSE_DIR="${WEBROOT}/.easysb"
BROWSE_TEMPLATE="${BROWSE_DIR}/browse.html"

log()  { printf '\033[36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m  ok %s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31m  x %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "以 root 运行 / run as root"
[ -n "$FTP_PASSWORD" ] || die "FTP_PASSWORD 未设置 / FTP_PASSWORD is required"

apt_install() {
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends "$@"
}

# --- caddy --------------------------------------------------------------------

install_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    ok "caddy $(caddy version | head -1)"
    return 0
  fi
  log "安装 caddy / installing caddy"
  apt-get update -qq
  apt_install debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --batch --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt_install caddy
  ok "$(caddy version | head -1)"
}

write_caddyfile() {
  log "写站点配置 / writing $CADDYFILE"
  mkdir -p "$(dirname "$CADDYFILE")"
  cat > "$CADDYFILE" <<EOF
# EasySB 软件源 / EasySB package sources
# 由 packaging/server/provision.sh 生成，手工改动会被下一次置备覆盖。
# Generated by packaging/server/provision.sh; manual edits are overwritten.
${SITE_DOMAIN} {
	encode zstd gzip
	root * ${WEBROOT}

	# 点号开头的文件（FTP 的同步状态文件、站点模板）不对外，只留给上传客户端与 Caddy。
	# Dotfiles - the FTP sync state file, the site template - stay away from readers.
	@hidden path /.*
	respond @hidden 404

	# 站点图标也住在被挡住的那个点目录里，只有根目录要显它，于是单开一条精确路径的路由。
	# Caddy 按路径的具体程度排序，精确路径排在 '@hidden path /.*' 通配之前，图标照发，
	# 列表里也不会平白多出一行。
	# The icon lives in the hidden dot-directory too. It gets an exact-path route of its own;
	# Caddy sorts an exact path ahead of the '@hidden path /.*' wildcard, so the icon is
	# served while the listing gains no extra entry.
	handle /favicon.svg {
		root * ${BROWSE_DIR}
		file_server
	}

	file_server {
		# 路径挡住了，列表里仍然会把它们列成点不开的条目，所以再从列表里摘掉。hide 不带
		# 分隔符时按路径分量做 filepath.Match，'.*' 于是匹配任意一层里的点开头的名字。
		# Out of reach is not enough: they would still be listed as entries that go nowhere.
		# A hide pattern without a separator is matched against each path component with
		# filepath.Match, so '.*' catches a dot-name at any depth.
		hide .*
		browse ${BROWSE_TEMPLATE}
	}
}
EOF
  caddy fmt --overwrite "$CADDYFILE" >/dev/null
  caddy validate --config "$CADDYFILE" >/dev/null || die "Caddyfile 校验失败 / invalid Caddyfile"
  ok "配置有效 / config valid"
}

start_caddy() {
  systemctl enable caddy >/dev/null 2>&1 || true
  if systemctl is-active --quiet caddy; then
    systemctl reload caddy || systemctl restart caddy
  else
    systemctl restart caddy
  fi
  ok "caddy 运行中 / caddy is running"
}

# --- 站点根目录 / the site root ------------------------------------------------

make_webroot() {
  log "建立站点根目录 / creating $WEBROOT"
  # linux 下按发行版分目录（linux/<发行版>/…），与 Docker 官方源一样；pacman 仍按架构分，
  # bin 放发布压缩包。
  # linux holds one subtree per distribution (linux/<distro>/...), like Docker's official
  # sources; pacman stays per-architecture and bin carries the release tarballs.
  mkdir -p "$WEBROOT"/{linux,pacman,bin} "$(dirname "$BROWSE_TEMPLATE")"
  ok "$WEBROOT/{linux,pacman,bin,.easysb}"

  # 源从前是扁平的 apt/ 与 rpm/<架构>/，公钥、easysb.repo 也散在根上。换成分发行版的
  # linux/ 之后这些路径没人再写。发布时的整棵替换也会收走它们，这里再收一遍是为了让只跑
  # 过置备、还没发布过的站点也是干净的。与新布局同名的文件不动。
  # The sources used to be a flat apt/ and rpm/<arch>/, with the key and easysb.repo loose at
  # the root. Nothing writes those paths after the move to the per-distribution linux/. The
  # release swap retires them too; removing them here keeps a freshly provisioned box, which
  # has not been released to yet, clean as well. Names the new layout uses are left alone.
  local stale
  for stale in apt rpm easysb.repo RPM-GPG-KEY-easysb; do
    if [ -e "$WEBROOT/$stale" ]; then
      rm -rf "$WEBROOT/$stale"
      warn "删除旧布局的 $stale / removed the old-layout $stale"
    fi
  done

  # 站点首页曾经是这份静态文件。file_server 只要见到 index.html 就直接发它，放着不管
  # 的话模板永远轮不到渲染，所以在置备时删掉。
  # The home page used to be this static file. file_server serves index.html whenever it
  # exists, which would shadow the template forever, so provisioning removes it.
  if [ -e "$WEBROOT/index.html" ]; then
    rm -f "$WEBROOT/index.html"
    warn "删除已被模板取代的首页 / removed the index.html the template replaced"
  fi

  # 图标以前直接放在站点根，会作为一行列在首页里。现在它随模板一起住进 .easysb/，根上那份
  # 旧文件得在这里收走。
  # The icon used to sit at the site root, where it showed up as a row on the home page. It
  # now lives in .easysb/ next to the template, so the stale copy at the root goes away here.
  if [ -e "$WEBROOT/favicon.svg" ]; then
    rm -f "$WEBROOT/favicon.svg"
    warn "删除站点根上多余的图标 / removed the stray icon at the site root"
  fi
}

# 模板缺失时补一份最简的目录列表，让站点先能打开。发布工作流把真正的模板上传到这里
# （dist/repo/.easysb/browse.html），所以这份占位符只在「刚置备、还没发布过」期间存在。
# A minimal listing so the site opens before anything has been uploaded. The release
# workflow puts the real template here (dist/repo/.easysb/browse.html), so this
# placeholder only exists between provisioning and the first release.
write_browse_template() {
  if [ -s "$BROWSE_TEMPLATE" ]; then
    ok "站点模板已就位 / site template in place"
    return 0
  fi
  log "写站点模板占位符 / writing a placeholder site template"
  cat > "$BROWSE_TEMPLATE" <<'EOF'
<!DOCTYPE html>
<html>
	<head>
		<title>{{html .Name}} - EasySB repository</title>
		<link rel="icon" href="/favicon.svg" type="image/svg+xml">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<h1>{{html .Name}}</h1>
		<p>EasySB package sources: /linux, /pacman, /bin</p>
		<ul>
			{{- range .Items}}
			<li><a href="{{html .URL}}">{{html .Name}}</a></li>
			{{- end}}
		</ul>
	</body>
</html>
EOF
  ok "$BROWSE_TEMPLATE"
}

# --- vsftpd -------------------------------------------------------------------

install_vsftpd() {
  if ! command -v vsftpd >/dev/null 2>&1; then
    log "安装 vsftpd / installing vsftpd"
    apt-get update -qq
    apt_install vsftpd openssl
  fi

  log "准备 FTP 证书 / preparing the FTP certificate"
  if [ ! -s "$TLS_CERT" ] || [ ! -s "$TLS_KEY" ]; then
    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
      -keyout "$TLS_KEY" -out "$TLS_CERT" \
      -subj "/CN=${SITE_DOMAIN}" >/dev/null 2>&1
    chmod 0600 "$TLS_KEY"
  fi
  ok "$TLS_CERT"

  log "写 vsftpd 配置 / writing $VSFTPD_CONF"
  [ -f "${VSFTPD_CONF}.orig" ] || cp -f "$VSFTPD_CONF" "${VSFTPD_CONF}.orig" 2>/dev/null || true
  cat > "$VSFTPD_CONF" <<EOF
# EasySB 发布上传 / EasySB release upload. Generated by provision.sh.
listen=YES
listen_ipv6=NO

# 本地账号登录，但只允许 $FTP_USER，并且被锁在自己的家目录里。
# Local accounts only, restricted to $FTP_USER, chrooted into its home.
local_enable=YES
write_enable=YES
chroot_local_user=YES
allow_writeable_chroot=YES
check_shell=NO
userlist_enable=YES
userlist_deny=NO
userlist_file=/etc/vsftpd.userlist

# 登录必须走 TLS（显式 FTPS），数据通道保持兼容。
# Login must use TLS (explicit FTPS); the data channel stays compatible.
# 不锁定 TLS 版本：Ubuntu 24.04 的 vsftpd 3.0.3 没有 ssl_tlsv1_2 这个选项，写了会以
# «bad config» 直接退出 2，而且不留任何日志。不写则自动协商可用的最高版本。
# No TLS version is pinned: vsftpd 3.0.3 on Ubuntu 24.04 has no ssl_tlsv1_2 option and
# exits 2 on it without logging anything. Left out, the best version is negotiated.
ssl_enable=YES
force_local_logins_ssl=YES
force_local_data_ssl=NO
require_ssl_reuse=NO
rsa_cert_file=${TLS_CERT}
rsa_private_key_file=${TLS_KEY}

# 被动模式：客户端连回本域名，端口范围固定，便于放行。
# Passive mode: clients dial the domain back on a fixed port range.
pasv_enable=YES
pasv_address=${SITE_DOMAIN}
pasv_min_port=${FTP_PASV_MIN}
pasv_max_port=${FTP_PASV_MAX}

local_umask=022
xferlog_enable=YES
connect_from_port_20=NO
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
EOF

  printf '%s\n' "$FTP_USER" > /etc/vsftpd.userlist
  mkdir -p /var/run/vsftpd/empty

  log "建立 FTP 账号 / creating the FTP account"
  if id "$FTP_USER" >/dev/null 2>&1; then
    usermod -d "$WEBROOT" -s "$FTP_SHELL" "$FTP_USER"
  else
    # -U 保证有一个同名组，下面按「用户:」改属主时不依赖 login.defs 的默认值。
    # -U guarantees a same-name group, so the chown below does not depend on
    # login.defs defaults.
    useradd -U -d "$WEBROOT" -s "$FTP_SHELL" -M "$FTP_USER"
  fi
  printf '%s:%s\n' "$FTP_USER" "$FTP_PASSWORD" | chpasswd
  ok "$FTP_USER -> $WEBROOT"

  # vsftpd 判 shell 那一关我们关掉了（check_shell=NO），但 Debian / Ubuntu 的
  # /etc/pam.d/vsftpd 还挂了一道 pam_shells，它要求账号的 shell 出现在 /etc/shells
  # 里，否则登录一律 530。nologin 通常不在那份名单里，补进去。
  # vsftpd's own shell check is off (check_shell=NO), but Debian / Ubuntu also wire
  # pam_shells into /etc/pam.d/vsftpd, which rejects any account whose shell is not listed
  # in /etc/shells with a 530. nologin is usually absent from that list, so add it.
  grep -qxF "$FTP_SHELL" /etc/shells 2>/dev/null || printf '%s\n' "$FTP_SHELL" >> /etc/shells

  log "调整站点根目录属主 / fixing ownership of $WEBROOT"
  chown -R "$FTP_USER": "$WEBROOT"
  chmod -R a+rX "$WEBROOT"
  ok "caddy 可读，FTP 可写 / readable by caddy, writable over FTP"
}

start_vsftpd() {
  systemctl enable vsftpd >/dev/null 2>&1 || true
  # restart 成功只说明进程起过，服务仍可能立刻退出，所以要回查一次状态。
  # A successful restart only means the process started; it can exit right after, so
  # the state is read back instead of assumed.
  if systemctl restart vsftpd && systemctl is-active --quiet vsftpd; then
    ok "vsftpd 运行中 / vsftpd is running"
  else
    warn "vsftpd 未能保持运行 / vsftpd did not stay up (see the self-check below)"
  fi
}

# 自检 / self-check. Provisioning is only useful if the ports the release workflow and
# the package managers dial are actually listening, so print what is bound and let the
# local caddy answer once. If port 21 is missing here, the unit failed to keep the
# listener up; if it is present here but refused from outside, a provider firewall is
# in the way.
verify() {
  log "自检 / verifying"
  local unit
  for unit in caddy vsftpd; do
    printf '  %-7s %s\n' "$unit" "$(systemctl is-active "$unit" 2>&1) / $(systemctl is-enabled "$unit" 2>&1)"
  done
  # A unit that reported success on restart can still fail right after, so show why.
  for unit in caddy vsftpd; do
    if ! systemctl is-active --quiet "$unit"; then
      echo "  --- journalctl -u $unit ---"
      journalctl -u "$unit" -n 25 --no-pager 2>&1 | sed 's/^/    /'
    fi
  done
  # 配置项写错时 vsftpd 既不写 journal 也不写 stderr，只留一个退出码。所以单元没起来
  # 时，把 systemd 记录的退出码和一次前台运行的结果打出来：退出码 124 表示前台运行
  # 被 timeout 收回，也就是它本身能正常服务，问题在别处（多为端口被占或 provider
  # 防火墙）；退出码 2 表示配置里有它不认识的选项。
  # A bad option makes vsftpd exit without writing to the journal or stderr, leaving only
  # an exit code. So when the unit is down, the recorded exit status and one foreground
  # run are printed: 124 means timeout reclaimed a healthy server (look at the port or a
  # provider firewall instead), 2 means an unknown option in the config.
  if ! systemctl is-active --quiet vsftpd; then
    printf '  vsftpd 版本 / version: %s\n' "$("$(command -v vsftpd)" -v 2>&1 | head -1)"
    systemctl show vsftpd -p ExecMainStatus,ExecMainCode 2>&1 | sed 's/^/    /'
    local out rc conf
    for conf in "$VSFTPD_CONF" "${VSFTPD_CONF}.orig"; do
      [ -r "$conf" ] || continue
      out="$(mktemp)"
      set +e
      timeout 2 "$(command -v vsftpd)" "$conf" >"$out" 2>&1
      rc=$?
      set -e
      printf '    %s rc=%s\n' "$conf" "$rc"
      sed 's/^/      /' "$out"
      rm -f "$out"
    done
  fi
  if command -v ss >/dev/null 2>&1; then
    echo "  listeners:"
    ss -lntp 2>/dev/null | awk 'NR==1 || /:(21|80|443)[[:space:]]/ {printf "    %s\n", $0}'
  fi
  # 走 HTTPS 而不是 http://127.0.0.1/：caddy 会把明文请求 308 到 https，跟过去核实才有
  # 意义。--resolve 让它连本机，不必依赖公网 DNS 与回环路由；-k 是因为证书由 caddy 现签。
  # The checks speak HTTPS rather than http://127.0.0.1/, because caddy 308s plaintext
  # requests to it. --resolve keeps the request on this box and -k covers the certificate
  # caddy issues on the spot.
  local -a caddycurl=(curl -sk --resolve "${SITE_DOMAIN}:443:127.0.0.1" "https://${SITE_DOMAIN}/")
  printf '  caddy local https: %s\n' \
    "$("${caddycurl[@]}" -o /dev/null -w '%{http_code}' || echo n/a)"
  # 首页由模板渲染，模板缺失时 Caddy 直接 500。发布前渲染的是占位符，所以「no」要么是
  # 还没发布，要么是模板没被上传，两种情况都不代表站点坏了。
  # The home page comes from the template and a missing file makes Caddy 500. Before the
  # first release the placeholder is what gets rendered, so "no" means either nothing has
  # been published yet or the template never arrived; neither means the site is broken.
  printf '  首页含安装说明 / home page carries the notes: %s\n' \
    "$("${caddycurl[@]}" | grep -qF 'Install EasySB' && echo yes || echo no)"
  # 用发布工作流那套凭据在本机真登一次：能列出目录说明口令与 PAM 都没问题，剩下就只是
  # provider 侧防火墙；被拒则把 PAM 与 shell 名单一并打出来。
  # Log in locally with the release workflow's own credentials: a listing means the
  # password and PAM are fine and only a provider firewall can still be at fault; a
  # rejection prints the PAM stack and the shells list.
  printf '  FTP 本机登录 / local FTP login: '
  # --ftp-ssl-control 只给控制通道加密，正好对应配置里的 force_local_data_ssl=NO，
  # 这样失败一定出在登录本身，不会混进数据通道的问题。
  # --ftp-ssl-control encrypts the control channel only, matching force_local_data_ssl=NO,
  # so a failure points at the login itself rather than the data channel.
  if curl -sS -k --ftp-ssl-control --user "$FTP_USER:$FTP_PASSWORD" \
       "ftp://127.0.0.1/" >/dev/null 2>&1; then
    echo "ok"
  else
    echo "FAILED"
    printf '    /etc/vsftpd.userlist: %s\n' "$(tr '\n' ' ' < /etc/vsftpd.userlist 2>/dev/null)"
    printf '    %s 的 shell: %s\n' "$FTP_USER" "$(getent passwd "$FTP_USER" | cut -d: -f7)"
    echo "    /etc/shells: $(tr '\n' ' ' < /etc/shells)"
    echo "    --- /etc/pam.d/vsftpd ---"
    sed 's/^/      /' /etc/pam.d/vsftpd 2>&1
    journalctl --since '-2 min' --no-pager 2>/dev/null | grep -i vsftpd | tail -10 | sed 's/^/      /'
  fi
  printf '  站点根目录属主 / webroot owner: %s\n' "$(stat -c '%U:%G %a' "$WEBROOT")"
  printf '  vsftpd 用户列表 / vsftpd userlist: %s\n' "$(cat /etc/vsftpd.userlist 2>/dev/null | tr '\n' ' ')"
}

summary() {
  cat <<EOF

置备完成 / provisioned
  站点 / site      https://${SITE_DOMAIN}
  根目录 / root    ${WEBROOT}
  源 / sources     https://${SITE_DOMAIN}/linux, /pacman, /bin
  FTP 账号 / user  ${FTP_USER}  被动端口 / passive ports ${FTP_PASV_MIN}-${FTP_PASV_MAX}

发布工作流用 FTPS 连接到 21 端口上传；请确认云厂商防火墙放行了 21、${FTP_PASV_MIN}-${FTP_PASV_MAX}、80 与 443。
The release workflow uploads over FTPS on port 21; make sure the provider firewall
allows 21, ${FTP_PASV_MIN}-${FTP_PASV_MAX}, 80 and 443.
EOF
}

install_caddy
make_webroot
write_browse_template
write_caddyfile
install_vsftpd
start_caddy
start_vsftpd
verify
summary
