#!/usr/bin/env bash
# ==============================================================================
#  EasySB 发布服务器置备 / provision the EasySB release server
# ------------------------------------------------------------------------------
#  在一台 Debian / Ubuntu 主机上准备软件源站点，全部步骤可重复执行：
#    - 安装 caddy，写站点配置，用自动签发的证书对外提供 HTTPS
#    - 建立站点根目录与 apt / rpm / pacman / bin 四个子目录
#    - 安装 vsftpd 并建一个只能写站点根的 FTP 账号，供发布工作流上传
#
#  Prepares a Debian / Ubuntu host to serve the package sources. Every step is
#  idempotent:
#    - install caddy, write the site config, serve HTTPS with an automatic certificate
#    - create the site root and its apt / rpm / pacman / bin subtrees
#    - install vsftpd and one FTP account confined to the site root, for the release
#      workflow to upload through
#
#  用法 / Usage:
#    SITE_DOMAIN=sb.kejizero.xyz FTP_PASSWORD=... bash provision.sh
#
#  需要 root；FTP_PASSWORD 必填，工作流的 FTP 步骤用同一个口令。
#  Run as root. FTP_PASSWORD is required and must match the workflow's FTP secret.
# ==============================================================================

set -euo pipefail

SITE_DOMAIN="${SITE_DOMAIN:-sb.kejizero.xyz}"
WEBROOT="${WEBROOT:-/var/www/${SITE_DOMAIN}}"
FTP_USER="${FTP_USER:-easysb}"
FTP_PASSWORD="${FTP_PASSWORD:-}"
FTP_PASV_MIN="${FTP_PASV_MIN:-40000}"
FTP_PASV_MAX="${FTP_PASV_MAX:-40100}"

TLS_CERT=/etc/ssl/certs/easysb-ftp.crt
TLS_KEY=/etc/ssl/private/easysb-ftp.key
CADDYFILE=/etc/caddy/Caddyfile
VSFTPD_CONF=/etc/vsftpd.conf

log()  { printf '\033[36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m  ok %s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31m  x %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "以 root 运行 / run as root"
[ -n "$FTP_PASSWORD" ] || die "FTP_PASSWORD 未设置 / FTP_PASSWORD is required"

apt_install() {
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends "$@"
}

# --- caddy --------------------------------------------------------------------

install_caddy() {
  if command -v caddy >/dev/null 2>&1; then
    ok "caddy $(caddy version | head -1)"
    return 0
  fi
  log "安装 caddy / installing caddy"
  apt-get update -qq
  apt_install debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --batch --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt_install caddy
  ok "$(caddy version | head -1)"
}

write_caddyfile() {
  log "写站点配置 / writing $CADDYFILE"
  mkdir -p "$(dirname "$CADDYFILE")"
  cat > "$CADDYFILE" <<EOF
# EasySB 软件源 / EasySB package sources
# 由 packaging/server/provision.sh 生成，手工改动会被下一次置备覆盖。
# Generated by packaging/server/provision.sh; manual edits are overwritten.
${SITE_DOMAIN} {
	encode zstd gzip
	root * ${WEBROOT}

	# 发布状态文件等点号开头的文件不对外，只留给上传客户端。
	# Dotfiles such as the deploy state file stay private to the upload client.
	@hidden path /.*
	respond @hidden 404

	file_server browse
}
EOF
  caddy fmt --overwrite "$CADDYFILE" >/dev/null
  caddy validate --config "$CADDYFILE" >/dev/null || die "Caddyfile 校验失败 / invalid Caddyfile"
  ok "配置有效 / config valid"
}

start_caddy() {
  systemctl enable caddy >/dev/null 2>&1 || true
  if systemctl is-active --quiet caddy; then
    systemctl reload caddy || systemctl restart caddy
  else
    systemctl restart caddy
  fi
  ok "caddy 运行中 / caddy is running"
}

# --- 站点根目录 / the site root ------------------------------------------------

make_webroot() {
  log "建立站点根目录 / creating $WEBROOT"
  mkdir -p "$WEBROOT"/{apt,rpm,pacman,bin}
  ok "$WEBROOT/{apt,rpm,pacman,bin}"
}

# --- vsftpd -------------------------------------------------------------------

install_vsftpd() {
  if ! command -v vsftpd >/dev/null 2>&1; then
    log "安装 vsftpd / installing vsftpd"
    apt-get update -qq
    apt_install vsftpd openssl
  fi

  log "准备 FTP 证书 / preparing the FTP certificate"
  if [ ! -s "$TLS_CERT" ] || [ ! -s "$TLS_KEY" ]; then
    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
      -keyout "$TLS_KEY" -out "$TLS_CERT" \
      -subj "/CN=${SITE_DOMAIN}" >/dev/null 2>&1
    chmod 0600 "$TLS_KEY"
  fi
  ok "$TLS_CERT"

  log "写 vsftpd 配置 / writing $VSFTPD_CONF"
  [ -f "${VSFTPD_CONF}.orig" ] || cp -f "$VSFTPD_CONF" "${VSFTPD_CONF}.orig" 2>/dev/null || true
  cat > "$VSFTPD_CONF" <<EOF
# EasySB 发布上传 / EasySB release upload. Generated by provision.sh.
listen=YES
listen_ipv6=NO

# 本地账号登录，但只允许 $FTP_USER，并且被锁在自己的家目录里。
# Local accounts only, restricted to $FTP_USER, chrooted into its home.
local_enable=YES
write_enable=YES
chroot_local_user=YES
allow_writeable_chroot=YES
check_shell=NO
userlist_enable=YES
userlist_deny=NO
userlist_file=/etc/vsftpd.userlist

# 登录必须走 TLS（显式 FTPS），数据通道保持兼容。
# Login must use TLS (explicit FTPS); the data channel stays compatible.
ssl_enable=YES
force_local_logins_ssl=YES
force_local_data_ssl=NO
require_ssl_reuse=NO
ssl_tlsv1_2=YES
rsa_cert_file=${TLS_CERT}
rsa_private_key_file=${TLS_KEY}

# 被动模式：客户端连回本域名，端口范围固定，便于放行。
# Passive mode: clients dial the domain back on a fixed port range.
pasv_enable=YES
pasv_address=${SITE_DOMAIN}
pasv_min_port=${FTP_PASV_MIN}
pasv_max_port=${FTP_PASV_MAX}

local_umask=022
xferlog_enable=YES
connect_from_port_20=NO
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
EOF

  printf '%s\n' "$FTP_USER" > /etc/vsftpd.userlist
  mkdir -p /var/run/vsftpd/empty

  log "建立 FTP 账号 / creating the FTP account"
  if id "$FTP_USER" >/dev/null 2>&1; then
    usermod -d "$WEBROOT" -s /usr/sbin/nologin "$FTP_USER"
  else
    # -U 保证有一个同名组，下面按「用户:」改属主时不依赖 login.defs 的默认值。
    # -U guarantees a same-name group, so the chown below does not depend on
    # login.defs defaults.
    useradd -U -d "$WEBROOT" -s /usr/sbin/nologin -M "$FTP_USER"
  fi
  printf '%s:%s\n' "$FTP_USER" "$FTP_PASSWORD" | chpasswd
  ok "$FTP_USER -> $WEBROOT"

  log "调整站点根目录属主 / fixing ownership of $WEBROOT"
  chown -R "$FTP_USER": "$WEBROOT"
  chmod -R a+rX "$WEBROOT"
  ok "caddy 可读，FTP 可写 / readable by caddy, writable over FTP"
}

start_vsftpd() {
  systemctl enable vsftpd >/dev/null 2>&1 || true
  systemctl restart vsftpd
  ok "vsftpd 运行中 / vsftpd is running"
}

# 自检 / self-check. Provisioning is only useful if the ports the release workflow and
# the package managers dial are actually listening, so print what is bound and let the
# local caddy answer once. If port 21 is missing here, the unit failed to keep the
# listener up; if it is present here but refused from outside, a provider firewall is
# in the way.
verify() {
  log "自检 / verifying"
  local unit
  for unit in caddy vsftpd; do
    printf '  %-7s %s\n' "$unit" "$(systemctl is-active "$unit" 2>&1) / $(systemctl is-enabled "$unit" 2>&1)"
  done
  if command -v ss >/dev/null 2>&1; then
    echo "  listeners:"
    ss -lntp 2>/dev/null | awk 'NR==1 || /:(21|80|443)[[:space:]]/ {printf "    %s\n", $0}'
  fi
  printf '  caddy local http: %s\n' \
    "$(curl -s -o /dev/null -w '%{http_code}' -H "Host: ${SITE_DOMAIN}" http://127.0.0.1/ || echo n/a)"
  printf '  站点根目录属主 / webroot owner: %s\n' "$(stat -c '%U:%G %a' "$WEBROOT")"
  printf '  vsftpd 用户列表 / vsftpd userlist: %s\n' "$(cat /etc/vsftpd.userlist 2>/dev/null | tr '\n' ' ')"
}

summary() {
  cat <<EOF

置备完成 / provisioned
  站点 / site      https://${SITE_DOMAIN}
  根目录 / root    ${WEBROOT}
  源 / sources     https://${SITE_DOMAIN}/apt, /rpm, /pacman, /bin
  FTP 账号 / user  ${FTP_USER}  被动端口 / passive ports ${FTP_PASV_MIN}-${FTP_PASV_MAX}

发布工作流用 FTPS 连接到 21 端口上传；请确认云厂商防火墙放行了 21、${FTP_PASV_MIN}-${FTP_PASV_MAX}、80 与 443。
The release workflow uploads over FTPS on port 21; make sure the provider firewall
allows 21, ${FTP_PASV_MIN}-${FTP_PASV_MAX}, 80 and 443.
EOF
}

install_caddy
write_caddyfile
make_webroot
install_vsftpd
start_caddy
start_vsftpd
verify
summary
